//! The SDK registry: turns discovered upstream tools into typed Python bindings,
//! generates the importable `sdk.py`, and exposes routing metadata.

pub mod codegen;
pub mod keyset;
pub mod shape;
pub mod summary;

use std::collections::{BTreeMap, HashMap};

use serde_json::Value;

use crate::upstream::NamespacedTool;

use codegen::PyBinding;

/// All generated bindings plus a lookup from Python fn name to (server, tool).
pub struct SdkRegistry {
    pub bindings: Vec<PyBinding>,
    /// fn_name -> (server, tool_name)
    route: HashMap<String, (String, String)>,
}

impl SdkRegistry {
    /// Build the registry from discovered upstream tools (no config overrides).
    /// Retained for tests and callers that have no mutation overrides.
    #[cfg(test)]
    pub fn build(tools: &[NamespacedTool]) -> Self {
        Self::build_with_overrides(tools, &BTreeMap::new())
    }

    /// Build the registry from discovered upstream tools.
    ///
    /// `mutation_overrides` maps `(server, tool)` to an explicit mutation
    /// classification from config, taking precedence over annotations/heuristic.
    pub fn build_with_overrides(
        tools: &[NamespacedTool],
        mutation_overrides: &BTreeMap<(String, String), bool>,
    ) -> Self {
        let mut bindings = Vec::new();
        let mut route = HashMap::new();
        let mut seen = HashMap::<String, u32>::new();

        for nt in tools {
            let tool_json: Value = serde_json::to_value(&nt.tool).unwrap_or(Value::Null);
            let input_schema: Value = serde_json::to_value(&*nt.tool.input_schema)
                .unwrap_or_else(|_| Value::Object(Default::default()));
            let output_schema: Option<Value> = nt
                .tool
                .output_schema
                .as_ref()
                .and_then(|s| serde_json::to_value(&**s).ok());

            let annotations = tool_json.get("annotations");
            let config_override = mutation_overrides
                .get(&(nt.server.clone(), nt.tool.name.as_ref().to_string()))
                .copied();
            let is_mutation =
                codegen::classify_mutation(nt.tool.name.as_ref(), annotations, config_override);

            let summ = summary::from_description(&nt.tool);
            let mut binding = codegen::build_binding(
                &nt.server,
                nt.tool.name.as_ref(),
                &summ,
                &input_schema,
                output_schema.as_ref(),
                is_mutation,
            );

            // Disambiguate any accidental fn-name collisions across servers.
            let count = seen.entry(binding.fn_name.clone()).or_insert(0);
            if *count > 0 {
                let new_name = format!("{}_{}", binding.fn_name, count);
                binding.signature = binding.signature.replacen(&binding.fn_name, &new_name, 1);
                binding.fn_name = new_name;
            }
            *count += 1;

            route.insert(
                binding.fn_name.clone(),
                (binding.server.clone(), binding.tool_name.clone()),
            );
            bindings.push(binding);
        }

        Self { bindings, route }
    }

    /// Resolve a Python fn name back to (server, tool). Routing currently happens
    /// directly via the (server, tool) baked into `sdk.py`, so this is retained
    /// for diagnostics/tests.
    #[allow(dead_code)]
    pub fn resolve(&self, fn_name: &str) -> Option<&(String, String)> {
        self.route.get(fn_name)
    }

    /// Iterate `(fn_name, (server, tool))` routing pairs.
    pub fn routes(&self) -> impl Iterator<Item = (&String, &(String, String))> {
        self.route.iter()
    }

    /// `fn_name` -> declared-outputSchema key structure, for tools that declare
    /// one. Seeds return-field validation before any value is observed.
    pub fn seed_keysets(&self) -> std::collections::BTreeMap<String, keyset::KeySet> {
        let mut out = std::collections::BTreeMap::new();
        for b in &self.bindings {
            if let Some(ks) = &b.output_keyset {
                if !ks.is_empty() {
                    out.insert(b.fn_name.clone(), ks.clone());
                }
            }
        }
        out
    }

    /// Generate the importable `sdk.py` source.
    ///
    /// Each function packs its (sanitized) parameters back into the original MCP
    /// property names and dispatches through `_codemcp_dispatch`, a callable the
    /// worker injects into the module globals before user code runs.
    pub fn generate_sdk_py(&self) -> String {
        let mut out = String::new();
        out.push_str("# Auto-generated by codemcp. Do not edit.\n");
        out.push_str("from __future__ import annotations\n");
        out.push_str("from typing import Any, Literal  # noqa: F401\n\n");
        out.push_str("# Injected by the worker runtime: dispatch(server, tool, args) -> result.\n");
        out.push_str("def _codemcp_dispatch(server: str, tool: str, args: dict) -> Any:\n");
        out.push_str("    raise RuntimeError('codemcp dispatch not initialized')\n\n\n");

        // Set of generated fn names classified as mutating (write) tools. The
        // worker's pre-flight validator uses this to require explicit
        // `allow_mutations` authorization before any write executes.
        out.push_str("# Generated fn names that mutate state (require allow_mutations).\n");
        out.push_str("_codemcp_mutations = {\n");
        for b in &self.bindings {
            if b.is_mutation {
                out.push_str(&format!("    {:?},\n", b.fn_name));
            }
        }
        out.push_str("}\n\n\n");

        for b in &self.bindings {
            out.push_str(&b.signature);
            out.push('\n');
            // docstring summary
            let doc = b.summary.replace('\\', "\\\\").replace('"', "\\\"");
            out.push_str(&format!("    \"\"\"{doc}\"\"\"\n"));
            // build args dict mapping mcp_name -> py_name, skipping None optionals
            out.push_str("    _args: dict[str, Any] = {}\n");
            for p in &b.params {
                if p.required {
                    out.push_str(&format!("    _args[{:?}] = {}\n", p.mcp_name, p.py_name));
                } else {
                    out.push_str(&format!("    if {} is not None:\n", p.py_name));
                    out.push_str(&format!(
                        "        _args[{:?}] = {}\n",
                        p.mcp_name, p.py_name
                    ));
                }
            }
            // Forward universal kwargs (timeout_ms, ...) into _args so the
            // dispatcher can honour them. Unknown extras are silently dropped
            // to keep the tool's own schema authoritative.
            out.push_str(
                "    for _k in (\"timeout_ms\",):\n\
                 \x20       if _k in _extra:\n\
                 \x20           _args[_k] = _extra[_k]\n",
            );
            out.push_str(&format!(
                "    return _codemcp_dispatch({:?}, {:?}, _args)\n\n\n",
                b.server, b.tool_name
            ));
        }

        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rmcp::model::Tool;
    use std::sync::Arc;

    fn tool(name: &str, desc: &str, schema: Value) -> NamespacedTool {
        let obj = schema.as_object().cloned().unwrap_or_default();
        let t = Tool::new(name.to_string(), desc.to_string(), Arc::new(obj));
        NamespacedTool {
            server: "everything".to_string(),
            tool: t,
        }
    }

    #[test]
    fn generates_valid_python_structure() {
        let tools = vec![tool(
            "get-sum",
            "Returns the sum of two numbers",
            serde_json::json!({
                "type": "object",
                "properties": {"a": {"type": "integer"}, "b": {"type": "integer"}},
                "required": ["a", "b"]
            }),
        )];
        let reg = SdkRegistry::build(&tools);
        assert_eq!(reg.bindings.len(), 1);
        let src = reg.generate_sdk_py();
        assert!(src.contains(
            "def everything_get_sum(a: int, b: int, **_extra: Any) -> dict[str, Any]:"
        ));
        assert!(src.contains("_codemcp_dispatch(\"everything\", \"get-sum\", _args)"));
        assert!(src.contains("_codemcp_mutations = {"));
        assert!(reg.resolve("everything_get_sum").is_some());
        // A read-verb tool is not in the mutation set.
        assert!(!reg.bindings[0].is_mutation);
    }

    #[test]
    fn mutation_tools_emitted_in_set() {
        let schema = serde_json::json!({
            "type": "object",
            "properties": {"title": {"type": "string"}},
            "required": ["title"]
        });
        let tools = vec![
            tool("create-issue", "Create an issue", schema.clone()),
            tool("get-issue", "Read an issue", schema),
        ];
        let reg = SdkRegistry::build(&tools);
        let src = reg.generate_sdk_py();
        assert!(src.contains("\"everything_create_issue\","));
        assert!(!src.contains("\"everything_get_issue\","));
    }

    #[test]
    fn mutation_override_forces_classification() {
        let schema = serde_json::json!({"type": "object", "properties": {}});
        let tools = vec![tool("get-thing", "Read a thing", schema)];
        let mut overrides = BTreeMap::new();
        overrides.insert(("everything".to_string(), "get-thing".to_string()), true);
        let reg = SdkRegistry::build_with_overrides(&tools, &overrides);
        assert!(reg.bindings[0].is_mutation);
        assert!(reg.generate_sdk_py().contains("\"everything_get_thing\","));
    }
}
